### ISSUE TITLE
What's the use of "tag" options

### ISSUE THREAD

**Issue by splanard** [iVantage/grunt-svn-bump#4]
Hello,
I tried using grunt-svn-bump. But the task doesn't tag the current version before "bumping" to the next one. The 'tag' options seems to have no effect at all.

**Comment by jtrussell** [comment]
You're correct. The README is way out of date - mostly as it existed when we forked from a different project that bumped for git. We've moved tagging to a separate task entirely: https://github.com/iVantage/grunt-svn-bump

There's also [an entire release task](https://github.com/ivantage/grunt-ivantage-svn-release) if you're interested that pulls together bumping, changelog creation, and tagging.

Apologies for the confusion, we'll get the README fixed up.
