### ISSUE TITLE
Bump a specific version ?

### ISSUE THREAD

**Issue by splanard** [iVantage/grunt-svn-bump#5]
That's more a question than an issue : is there a way to bump a specific version instead of performing a patch/minor/major upgrade ?
Like, using http://www.bg4technology.appspot.com/www.npmjs.com/package/grunt-bump, I could use grunt bump --setversion=2.0.1 to specify the next version to 2.0.1, no matter the original version.

**Comment by jtrussell** [comment]
We don't have anything along those lines, sorry. If you're willing to implement it we'd be open to accepting a PR.
